last_scan_only = False
report_text = False
report_html = ''
junit_xml = ''
junit_type = 'pols'
# output_sarif = ''
bd_url = ''
bd_apitoken = ''
bd_trustcert = False
fail_on_policies = []
polsevs = ['UNSPECIFIED', 'TRIVIAL', 'MINOR', 'MAJOR', 'CRITICAL', 'BLOCKER', ]
